export const routePaths = {
  home: '/',
  catalog: '/catalog',
  productDetail: '/product/:id',
  cart: '/cart',
  checkout: '/checkout',
  orderTracking: '/order-tracking',
  orderConfirmation: '/order-confirmation',
  bikeSelection: '/bike-selection',
  calculator: '/calculator',
  login: '/login',
  passwordReset: '/password-reset',
  favorites: '/favorites',
  aiChat: '/ai-chat',
  adminPanel: '/admin',
  // Тестовые/сервисные
  mobileTest: '/test/mobile',
  performanceTest: '/test/performance',
  testAuth: '/test/auth',
  testFavoritesAuth: '/test/favorites-auth',
  testProfileDropdown: '/test/profile-dropdown',
  testButton: '/test/button',
  testBuycycle: '/test/buycycle',
} as const