ALTER TABLE bikes ADD COLUMN price_eur REAL;
ALTER TABLE bikes ADD COLUMN price_rub REAL;

CREATE TABLE IF NOT EXISTS currency_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rate REAL NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
