-- Migration: Sprint 2 Manager Copilot
-- Description: Adds negotiations table and ensures tasks table has correct structure for AI Manager Copilot.

-- 1. Create negotiations table if not exists
-- This table stores the context of negotiations with sellers, including chat transcripts and AI analysis.
CREATE TABLE IF NOT EXISTS public.negotiations (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id text REFERENCES public.orders(id), -- Links to orders.id (text)
    seller_platform text, -- e.g. 'telegram', 'whatsapp', 'kleinanzeigen'
    start_price numeric(12, 2),
    final_price numeric(12, 2),
    success boolean,
    chat_transcript text, -- Full text or JSON of the chat
    seller_contact_info text, -- Extracted contact info
    ocr_metadata jsonb, -- Raw OCR results from Gemini
    last_analyzed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT negotiations_pkey PRIMARY KEY (id)
);

-- 2. Add columns to tasks for AI context
-- These fields help identify which tasks were generated by AI and for what component.
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS ai_generated boolean DEFAULT false;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS bike_component text; -- e.g. 'frame', 'battery', 'suspension'
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS confidence_score numeric(5,2); -- AI confidence level (0-100)

-- 3. Create index for fast lookups
CREATE INDEX IF NOT EXISTS idx_negotiations_order_id ON public.negotiations(order_id);
