const EVENT_TYPE_MAP = {
    session_start: 'session_start',
    page_view: 'page_view',
    first_click: 'first_click',
    ui_click: 'ui_click',
    catalog_view: 'catalog_view',
    product_view: 'product_view',
    impression: 'impression',
    view: 'detail_open',
    click: 'detail_open',
    detail_open: 'detail_open',
    hover: 'hover',
    scroll: 'gallery_swipe',
    gallery_swipe: 'gallery_swipe',
    scroll_stop: 'scroll_stop',
    favorite: 'favorite',
    add_to_cart: 'add_to_cart',
    cart_add: 'add_to_cart',
    share: 'share',
    dwell: 'dwell',
    checkout_start: 'checkout_start',
    checkout_step: 'checkout_step',
    checkout_submit_attempt: 'checkout_submit_attempt',
    checkout_submit_success: 'checkout_submit_success',
    checkout_submit_failed: 'checkout_submit_failed',
    checkout_validation_error: 'checkout_validation_error',
    checkout_field_error: 'checkout_field_error',
    checkout_abandon: 'checkout_abandon',
    form_seen: 'form_seen',
    form_first_input: 'form_first_input',
    form_submit_attempt: 'form_submit_attempt',
    form_validation_error: 'form_validation_error',
    web_vital: 'web_vital',
    api_latency: 'api_latency',
    lead_created: 'lead_created',
    booking_start: 'booking_start',
    booking_success: 'booking_success',
    booking_failed: 'booking_failed',
    order: 'order',
    purchase: 'order',
    bounce: 'bounce'
};

const EVENT_PROFILE_WEIGHTS = {
    session_start: 0,
    page_view: 0,
    first_click: 2,
    ui_click: 0.2,
    catalog_view: 0.2,
    product_view: 6,
    impression: 0.1,
    scroll_stop: 1,
    hover: 1,
    gallery_swipe: 3,
    detail_open: 10,
    share: 50,
    favorite: 70,
    add_to_cart: 100,
    checkout_step: 4,
    checkout_submit_attempt: 8,
    checkout_submit_success: 20,
    checkout_submit_failed: -5,
    checkout_validation_error: -2,
    checkout_field_error: -2.5,
    checkout_abandon: -8,
    form_seen: 0,
    form_first_input: 0,
    form_submit_attempt: 0,
    form_validation_error: 0,
    web_vital: 0,
    api_latency: 0,
    order: 120,
    dwell: 15,
    bounce: -10
};

const DEFAULT_EVENT_LIMIT = 200;

module.exports = {
    EVENT_TYPE_MAP,
    EVENT_PROFILE_WEIGHTS,
    DEFAULT_EVENT_LIMIT
};
