const { createClient } = require('@supabase/supabase-js');
const { v4: uuidv4 } = require('uuid');

// Mock Dependencies
const SUPABASE_URL = 'https://lclalsznmrjgqsgaqtps.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjbGFsc3pubXJqZ3FzZ2FxdHBzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDk3ODkwOCwiZXhwIjoyMDc2NTU0OTA4fQ.NIGp4ueVE74uwmhFn1AH8yzhtVmm7SCRmDz2-2cBHqA';

// Mock Supabase Service
const mockSupabase = {
    supabase: createClient(SUPABASE_URL, SUPABASE_KEY)
};

// Mock Gemini
const mockGemini = {
    generateTechnicalTasks: async (name, snapshot) => {
        console.log('[MockGemini] Generating tasks for', name);
        return [
            "Check frame for cracks (Mock Task)",
            "Verify serial number (Mock Task)",
            "Test rear suspension (Mock Task)"
        ];
    }
};

// We need to inject these mocks into OrderDispatcher or just implement the logic inline for testing
// Since we can't easily inject without dependency injection, I will reimplement the core logic here for verification
// OR I can require the actual file and mock the requires if I use a test runner, but here I'll just reproduce the logic 
// to verify database interactions.

async function testFlow() {
    console.log('🚀 Starting Dispatch Flow Test...');
    const supabase = mockSupabase.supabase;

    // 1. Create Dummy User (Manager) if not exists
    console.log('1. Checking Managers...');
    const { data: managers } = await supabase
        .from('users')
        .select('*')
        .eq('role', 'manager');
    
    if (!managers || managers.length === 0) {
        console.log('❌ No managers found! Create a manager first.');
        return;
    }
    console.log(`✅ Found ${managers.length} managers.`);

    // 2. Create Dummy Order
    const orderCode = 'TEST-' + Math.floor(Math.random() * 10000);
    console.log(`2. Creating Dummy Order ${orderCode}...`);
    
    const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
            order_code: orderCode,
            status: 'awaiting_deposit',
            bike_name: 'Specialized Stumpjumper EVO',
            total_price_rub: 150000
        })
        .select()
        .single();

    if (orderError) {
        console.error('❌ Order Creation Failed:', orderError);
        return;
    }
    console.log('✅ Order Created:', order.id);

    // 3. Run "Dispatch" Logic (Simulated)
    console.log('3. Running Dispatch Logic...');
    
    // 3a. Find Best Manager
    // Simple load balancing: just pick first for test
    const bestManager = managers[0]; 
    console.log(`Assigning to ${bestManager.username} (${bestManager.id})`);

    await supabase
        .from('orders')
        .update({ assigned_manager: bestManager.id })
        .eq('id', order.id);

    // 3b. Generate Tasks
    const tasks = await mockGemini.generateTechnicalTasks(order.bike_name, {});
    const tasksToInsert = tasks.map(desc => ({
        order_id: order.id,
        title: desc,
        description: 'Generated by Test Script',
        completed: false,
        assigned_to: bestManager.id
    }));

    const { data: insertedTasks, error: taskError } = await supabase
        .from('tasks')
        .insert(tasksToInsert)
        .select();

    if (taskError) {
        console.error('❌ Task Insertion Failed:', taskError);
    } else {
        console.log(`✅ Created ${insertedTasks.length} tasks.`);
    }

    // 4. Clean up (Optional)
    console.log('4. Cleaning up...');
    await supabase.from('tasks').delete().eq('order_id', order.id);
    await supabase.from('orders').delete().eq('id', order.id);
    console.log('✅ Cleanup Done.');
}

testFlow();
